FROM        debian:buster

RUN         apt-get update
RUN         apt-get install -y \
                dumb-init \
                nginx
RUN         apt-get install -y \
                openssl

RUN         openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 \
            -subj "/C=KR/ST=Korea/L=Seoul/O=Seoul42/CN=kkim.42.fr" \
            -keyout /etc/ssl/private/kkim.key -out /etc/ssl/certs/kkim.crt
            

COPY        ./conf/nginx.conf       /etc/nginx/nginx.conf
COPY        ./conf/hosts            /etc/

ENTRYPOINT  ["/usr/bin/dumb-init"]

EXPOSE      443

CMD         ["nginx", "-g", "daemon off;"]

