version:   "3"
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: my_nginx:v.1.0.0
    ports:
      - "127.0.0.1:80:80"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  mysql:
    container_name: mariaDB
    build: ./requirements/mariadb
    image: my_mariadb:v.1.0.0
    volumes:
      - database:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

  wordpress:
    depends_on:
      - mysql
    container_name: wp-php7.3
    build: ./requirements/wordpress
    image: wp-php:v.1.0.0
    volumes:
      - wp:/var/www/wordpress
    ports:
      - "9000:9000"
    restart: on-failure
    env_file: 
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/plam/data/database
  wp:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/plam/data/wordpress