version: '2'

services:
  nginx:
    build: srcs/nginx/
    ports:
        - "80:80"
        - "443:443"
    networks:
        - frontend
  wordpress:
    build: srcs/wordpress/
    ports:
            - "9000:9000"
    volumes:
        - db:/usr/share/db
    networks:
        - frontend

volumes:
    db:
        external: true

networks:
    frontend:
        driver: bridge
    backend:
        driver: bridge