version: '3'
services:
    nginx:
        build : requirements/nginx/.
        ports:
            - '80:80'
        volumes:
            - ./requirements/nginx/conf/wordpress.conf:/etc/nginx/conf.d/default
            - ./logs/nginx:/var/log/nginx
        links:
            - wordpress
        restart: always

    mariadb:
        build: requirements/mariadb/.
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=inception_r_p
        restart: always

    wordpress:
        build: requirements/WordPress/.
        image: wordpress:4.7.1-php7.0-fpm:tag
        ports:
            - '9000:9000'
        volumes:
            - WordPress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mariadb
            - WORDPRESS_DB_PASSWORD=inception_r_p
        links:
            - mariadb
        restart: always

volumes:
    WordPress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/mochegri/data/WordPress'
    DB:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/mochegri/data/DB'
